// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NutriMetrics.Modules.CalorieTracking.Infrastructure.Database;

#nullable disable

namespace NutriMetrics.Modules.CalorieTracking.Infrastructure.Database.Migrations
{
    [DbContext(typeof(CalorieTrackingDbContext))]
    [Migration("20260722004320_AddUserIdToFoodItems")]
    partial class AddUserIdToFoodItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("NutriMetrics.Modules.CalorieTracking.Domain.Entities.FoodItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<double>("Calories")
                        .HasPrecision(10, 2)
                        .HasColumnType("double");

                    b.Property<double>("CarbohydratesGrams")
                        .HasPrecision(10, 2)
                        .HasColumnType("double");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<double>("FatGrams")
                        .HasPrecision(10, 2)
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<double>("ProteinGrams")
                        .HasPrecision(10, 2)
                        .HasColumnType("double");

                    b.Property<double>("ServingSizeGrams")
                        .HasPrecision(10, 2)
                        .HasColumnType("double");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FoodItems", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
