namespace NutriMetrics.Modules.CalorieTracking.Infrastructure.ExternalServices.CalorieNinjas;

using System.Net.Http.Json;
using System.Text.RegularExpressions;
using NutriMetrics.Modules.CalorieTracking.Domain.Contracts;
using NutriMetrics.Modules.CalorieTracking.Domain.Entities;
using NutriMetrics.Modules.CalorieTracking.Infrastructure.ExternalServices.CalorieNinjas.Dtos;

public class CalorieNinjasHttpClient : INutritionApiClient
{
    private readonly HttpClient _httpClient;
    private readonly ITranslationService _translationService;

    public CalorieNinjasHttpClient(HttpClient httpClient, ITranslationService translationService)
    {
        _httpClient = httpClient;
        _translationService = translationService;
    }

    public async Task<IEnumerable<FoodItem>> SearchFoodAsync(string query, CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(query))
        {
            return Enumerable.Empty<FoodItem>();
        }

        // 1. Translate the full query.
        var englishQuery = await _translationService.TranslateToEnglishAsync(query, cancellationToken);

        // 2. If query starts with a quantity token, translate the food phrase alone.
        // We'll synthesize quantity-preserving candidates first and keep quantity-stripped
        // candidates as late fallback only.
        string? englishWithoutLeadingToken = null;
        var queryWithoutLeadingToken = RemoveLeadingToken(query);
        if (!string.Equals(queryWithoutLeadingToken, query, StringComparison.OrdinalIgnoreCase))
        {
            englishWithoutLeadingToken = await _translationService.TranslateToEnglishAsync(queryWithoutLeadingToken, cancellationToken);
        }

        // 3. Try multiple candidates generated by generic normalization rules (no hardcoded dictionaries).
        var candidates = BuildCandidates(query, englishQuery, queryWithoutLeadingToken, englishWithoutLeadingToken);

        CalorieNinjasResponseDto? response = null;
        foreach (var candidate in candidates)
        {
            try
            {
                response = await _httpClient.GetFromJsonAsync<CalorieNinjasResponseDto>(
                    $"v1/nutrition?query={Uri.EscapeDataString(candidate)}",
                    cancellationToken
                );
            }
            catch (HttpRequestException)
            {
                continue;
            }

            if (response?.Items != null && response.Items.Count > 0)
            {
                break;
            }
        }

        if (response?.Items == null || response.Items.Count == 0)
        {
            return Enumerable.Empty<FoodItem>();
        }

        // 4. Map response to Domain
        return response.Items.Select(item => new FoodItem(
            userId: Guid.Empty, // Temporary - these are search results, not persisted
            name: item.Name,
            calories: item.Calories,
            proteinGrams: item.ProteinG,
            fatGrams: item.FatTotalG,
            carbohydratesGrams: item.CarbohydratesTotalG,
            servingSizeGrams: item.ServingSizeG
        ));
    }

    private static List<string> BuildCandidates(
        string originalQuery,
        string translatedQuery,
        string queryWithoutLeadingToken,
        string? translatedWithoutLeadingToken)
    {
        var candidates = new List<string>();

        // Highest priority: fully translated query (should preserve quantity semantics when possible).
        AddCandidateVariants(candidates, translatedQuery);

        // If we can isolate the food phrase translation, recompose with leading token from translated query
        // to preserve quantity before trying quantity-less fallbacks.
        var translatedLeadingToken = GetLeadingToken(translatedQuery);
        if (!string.IsNullOrWhiteSpace(translatedLeadingToken) && !string.IsNullOrWhiteSpace(translatedWithoutLeadingToken))
        {
            AddCandidateVariants(candidates, $"{translatedLeadingToken} {translatedWithoutLeadingToken}");
        }

        // Next, try original translated food phrase with original leading token.
        var originalLeadingToken = GetLeadingToken(originalQuery);
        if (!string.IsNullOrWhiteSpace(originalLeadingToken) && !string.IsNullOrWhiteSpace(translatedWithoutLeadingToken))
        {
            AddCandidateVariants(candidates, $"{originalLeadingToken} {translatedWithoutLeadingToken}");
        }

        // Then use original query as fallback before dropping quantity.
        AddCandidateVariants(candidates, originalQuery);

        // Quantity-less fallbacks are last resort.
        AddCandidateVariants(candidates, translatedWithoutLeadingToken, includeQuantityStrippedFallback: false);
        AddCandidateVariants(candidates, queryWithoutLeadingToken, includeQuantityStrippedFallback: false);

        return candidates;
    }

    private static void AddCandidateVariants(List<string> candidates, string? candidate, bool includeQuantityStrippedFallback = true)
    {
        if (string.IsNullOrWhiteSpace(candidate))
        {
            return;
        }

        var normalized = NormalizeSpaces(candidate);
        if (string.IsNullOrWhiteSpace(normalized))
        {
            return;
        }

        AddUnique(candidates, normalized);

        if (includeQuantityStrippedFallback)
        {
            var withoutNumericPrefix = RemoveLeadingNumericToken(normalized);
            if (!string.Equals(withoutNumericPrefix, normalized, StringComparison.OrdinalIgnoreCase))
            {
                AddUnique(candidates, withoutNumericPrefix);
            }

            var withoutLeadingToken = RemoveLeadingToken(normalized);
            if (!string.Equals(withoutLeadingToken, normalized, StringComparison.OrdinalIgnoreCase))
            {
                AddUnique(candidates, withoutLeadingToken);
            }
        }

        var singularized = SingularizeLastWord(normalized);
        if (!string.Equals(singularized, normalized, StringComparison.OrdinalIgnoreCase))
        {
            AddUnique(candidates, singularized);
        }

        if (includeQuantityStrippedFallback)
        {
            var withoutLeadingToken = RemoveLeadingToken(normalized);
            var singularizedWithoutPrefix = SingularizeLastWord(withoutLeadingToken);
            if (!string.IsNullOrWhiteSpace(singularizedWithoutPrefix)
                && !string.Equals(singularizedWithoutPrefix, withoutLeadingToken, StringComparison.OrdinalIgnoreCase))
            {
                AddUnique(candidates, singularizedWithoutPrefix);
            }
        }
    }

    private static void AddUnique(List<string> candidates, string value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return;
        }

        if (candidates.Any(c => string.Equals(c, value, StringComparison.OrdinalIgnoreCase)))
        {
            return;
        }

        candidates.Add(value);
    }

    private static string NormalizeSpaces(string value)
    {
        return Regex.Replace(value.Trim(), "\\s+", " ");
    }

    private static string RemoveLeadingNumericToken(string value)
    {
        var result = Regex.Replace(
            value,
            "^\\s*[+-]?\\d+(?:[.,]\\d+)?\\s+",
            string.Empty,
            RegexOptions.CultureInvariant);

        return NormalizeSpaces(result);
    }

    private static string RemoveLeadingToken(string value)
    {
        var result = Regex.Replace(
            value,
            "^\\s*[^\\s]+\\s+",
            string.Empty,
            RegexOptions.CultureInvariant);

        var normalized = NormalizeSpaces(result);
        return string.IsNullOrWhiteSpace(normalized) ? value.Trim() : normalized;
    }

    private static string? GetLeadingToken(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return null;
        }

        var match = Regex.Match(value, "^\\s*(?<token>[^\\s]+)", RegexOptions.CultureInvariant);
        if (!match.Success)
        {
            return null;
        }

        var token = match.Groups["token"].Value.Trim();
        return string.IsNullOrWhiteSpace(token) ? null : token;
    }

    private static string SingularizeLastWord(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return value;
        }

        var words = value.Split(' ', StringSplitOptions.RemoveEmptyEntries);
        if (words.Length == 0)
        {
            return value;
        }

        var last = words[^1];
        var singular = SingularizeWord(last);
        if (string.Equals(last, singular, StringComparison.OrdinalIgnoreCase))
        {
            return value;
        }

        words[^1] = singular;
        return string.Join(' ', words);
    }

    private static string SingularizeWord(string word)
    {
        if (word.Length <= 2)
        {
            return word;
        }

        if (Regex.IsMatch(word, "[A-Za-z]ies$", RegexOptions.CultureInvariant))
        {
            return word[..^3] + "y";
        }

        if (Regex.IsMatch(word, "[A-Za-z](ches|shes|xes|zes|ses|oes)$", RegexOptions.CultureInvariant))
        {
            return word[..^2];
        }

        if (Regex.IsMatch(word, "[A-Za-z]s$", RegexOptions.CultureInvariant) && !word.EndsWith("ss", StringComparison.OrdinalIgnoreCase))
        {
            return word[..^1];
        }

        return word;
    }

}